# Generated by Django 4.2.4 on 2023-08-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='gallery')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
    ]
